sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
before_script: |
  PKGNAME="rust_fixed_width" # must match with cargo.toml
  LOCAL="~/.local" # install here to avoid `sudo`
  KCOV_VERSION=v33
  export PATH=$LOCAL/bin:$PATH
script: cargo test --verbose
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libbfd-dev # required for `--verify`
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/$KCOV_VERSION.tar.gz &&
  tar xzf $KCOV_VERSION.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. &&
  make &&
  make install &&
  cd ../.. &&
  kcov --verify \
       --coveralls-id=$TRAVIS_JOB_ID \
       --exclude-pattern=/.cargo,/usr/lib \
       target/kcov target/debug/rust_fixed_width-*
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"