[package]
name = "fixed_width"
version = "0.1.0"
authors = ["yosefderay <yosefderay770@gmail.com>"]

[features]
default = ["in_memory"]
in_memory = []
spec = []
reader = ["spec"]
builder = ["spec"]
all = ["in_memory", "reader", "builder", "spec"]
