(function() {var implementors = {};
implementors["rust_fixed_width"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>IoError</a>&gt; for <a class='enum' href='rust_fixed_width/record/recognizers/enum.Error.html' title='rust_fixed_width::record::recognizers::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>IoError</a>&gt; for <a class='enum' href='rust_fixed_width/record/enum.Error.html' title='rust_fixed_width::record::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='rust_fixed_width/record/recognizers/enum.Error.html' title='rust_fixed_width::record::recognizers::Error'>RecognizerError</a>&gt; for <a class='enum' href='rust_fixed_width/record/enum.Error.html' title='rust_fixed_width::record::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='rust_fixed_width/padders/struct.Error.html' title='rust_fixed_width::padders::Error'>PadderError</a>&gt; for <a class='enum' href='rust_fixed_width/record/enum.Error.html' title='rust_fixed_width::record::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='rust_fixed_width/padders/enum.PaddingError.html' title='rust_fixed_width::padders::PaddingError'>PaddingError</a>&gt; for <a class='struct' href='rust_fixed_width/padders/struct.Error.html' title='rust_fixed_width::padders::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
