(function() {var implementors = {};
implementors["rust_fixed_width"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.Spec.html' title='rust_fixed_width::spec::Spec'>Spec</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.SpecBuilder.html' title='rust_fixed_width::spec::SpecBuilder'>SpecBuilder</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.RecordSpec.html' title='rust_fixed_width::spec::RecordSpec'>RecordSpec</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.RecordSpecBuilder.html' title='rust_fixed_width::spec::RecordSpecBuilder'>RecordSpecBuilder</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rust_fixed_width/spec/enum.PaddingDirection.html' title='rust_fixed_width::spec::PaddingDirection'>PaddingDirection</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.FieldSpec.html' title='rust_fixed_width::spec::FieldSpec'>FieldSpec</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/spec/struct.FieldSpecBuilder.html' title='rust_fixed_width::spec::FieldSpecBuilder'>FieldSpecBuilder</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rust_fixed_width/record/recognizers/enum.Error.html' title='rust_fixed_width::record::recognizers::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rust_fixed_width/padders/struct.Error.html' title='rust_fixed_width::padders::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
